### ISSUE TITLE
Updates & Fixes

### ISSUE THREAD

**Issue by JohnnyX071** [kqnan/UltraMinions#1]
Hello, the work that you have done is amazing. Thanks for updating this plugin to 1.19.1+. I wanted to ask if you are willing to keep updating it to other versions like 1.20 when it gets released. Also there are a few bugs that I wanted to be fixed such as saving. If the server crashes, the database gets corrupted or something and makes all minions armor stands.  Even on local saves. To reproduce it, use a local server and kill it by pressing x on the window. Thanks!!

**Comment by JohnnyX071** [comment]
Here is a translation:
你好，你所做的工作是惊人的。感谢您将此插件更新到 1.19.1+。我想问一下你是否愿意在它发布时继续更新到其他版本，比如 1.20。还有一些我想修复的错误，例如保存。如果服务器崩溃，数据库就会损坏或发生其他事情，并使所有小兵都变成盔甲架。即使在本地保存。要重现它，请使用本地服务器并通过在窗口上按 x 来终止它。谢谢！！

**Comment by kqnan** [comment]
> Here is a translation: 你好，你所做的工作是惊人的。感谢您将此插件更新到 1.19.1+。我想问一下你是否愿意在它发布时继续更新到其他版本，比如 1.20。还有一些我想修复的错误，例如保存。如果服务器崩溃，数据库就会损坏或发生其他事情，并使所有小兵都变成盔甲架。即使在本地保存。要重现它，请使用本地服务器并通过在窗口上按 x 来终止它。谢谢！！

我没有时间来继续这个项目了。这个插件能否兼容更高的版本取决于NBTAPI和Protocollib。关于数据库的问题，目前的解决方法是定时保存。事实上最好的方法是，当玩家放置小兵时，立刻保存，这样就不会丢失数据，但我要维护其他项目，没时间维护这个项目了。

**Comment by JohnnyX071** [comment]
我明白了，但是有没有办法修复一些错误？这可能是唯一令人惊叹的公开 ultraminions 重新编码。关于错误，即使自动保存也无法修复。正如我发现的那样，数据库没有损坏，但有时在重新启动后，小兵变成了盔甲架并且无法工作。如果我关闭并打开服务器，那么它们都很好，所以我真的不知道问题出在哪里。我希望你重新考虑至少修复一些错误，因为你的项目很棒，谢谢！


> > Here is a translation: 你好，你所做的工作是惊人的。感谢您将此插件更新到 1.19.1+。我想问一下你是否愿意在它发布时继续更新到其他版本，比如 1.20。还有一些我想修复的错误，例如保存。如果服务器崩溃，数据库就会损坏或发生其他事情，并使所有小兵都变成盔甲架。即使在本地保存。要重现它，请使用本地服务器并通过在窗口上按 x 来终止它。谢谢！！
> 
> 我没有时间来继续这个项目了。这个插件能否兼容更高的版本取决于NBTAPI和Protocollib。关于数据库的问题，目前的解决方法是定时保存。事实上最好的方法是，当玩家放置小兵时，立刻保存，这样就不会丢失数据，但我要维护其他项目，没时间维护这个项目了。

**Comment by JohnnyX071** [comment]
那么，您是否有机会在空闲时间支持该插件？

**Comment by kqnan** [comment]
> 那么，您是否有机会在空闲时间支持该插件？

实际上这个插件已经很完善了，而我也不会再短期内再为这个插件写代码了

**Comment by kqnan** [comment]
> 那么，您是否有机会在空闲时间支持该插件？

实际上这个插件现在很完善了，我不会在短期内再为这个插件写代码

**Comment by JohnnyX071** [comment]
我的意思是修复我提到的错误。除此之外没有其他bug。有时在重新启动后小兵会变成盔甲架，我必须重新启动 1-2 次才能让他们再次成为普通小兵

**Comment by JohnnyX071** [comment]
?

**Comment by JohnnyX071** [comment]
没有任何回应的错误？
